#!/bin/bash
# snap/hooks/install — Additions for config-file support in OCI-derived snaps
#
# This file contains the ADDITIONS needed to support operator configuration
# via snap config keys.  Merge these blocks into the existing install hook
# generated by docker-to-snap (which handles /etc/hosts advertisement).
#
# Replace all <PLACEHOLDERS> before use.
# Make executable: chmod +x snap/hooks/install
#
# See references/snap-config-guide.md §3 for the full guide.

set -e

# ─── (EXISTING docker-to-snap install hook content goes above this line) ──────
# The blocks below should be appended to the existing hook, not replace it.

# ─── 1. CREATE WRITABLE DIRECTORIES IN $SNAP_COMMON ──────────────────────────
# These directories persist across snap upgrades.

mkdir -p "$SNAP_COMMON/config"
# mkdir -p "$SNAP_COMMON/data"
# mkdir -p "$SNAP_COMMON/logs"
# mkdir -p "$SNAP_COMMON/certs"

# ─── 2. CREATE DEFAULT CONFIG FILE (FIRST INSTALL ONLY) ──────────────────────
# Use [ ! -f ... ] to skip if the file already exists, so that re-installing or
# refreshing the snap does not wipe operator customisations.

if [ ! -f "$SNAP_COMMON/config/<app>.conf" ]; then

    # ── Option A: Copy bundled default from $SNAP (preferred) ────────────────
    # Requires the default config to be shipped inside the snap.
    # In snapcraft.yaml, ensure the file is staged under snap/local/ or rootfs/:
    #   parts:
    #     oci-container:
    #       override-build: |
    #         craftctl default
    #         # (the default config is already in rootfs/etc/<app>/<app>.conf)
    #
    if [ -f "$SNAP/etc/<app>/<app>.conf" ]; then
        cp "$SNAP/etc/<app>/<app>.conf" "$SNAP_COMMON/config/<app>.conf"
    else
        # ── Option B: Generate minimal defaults from snap config keys ─────────
        # Used when no bundled config file is available in $SNAP.
        # Adjust keys and defaults to match the application.
        cat > "$SNAP_COMMON/config/<app>.conf" <<EOF
# <App> configuration — managed by snap hooks
# To change settings: snap set <snap-name> <key>=<value>
port=8080
log_level=info
EOF
    fi

fi

# ─── 3. SET INITIAL SNAP CONFIG DEFAULTS ─────────────────────────────────────
# Populate snap config keys with defaults so `snap get <snap-name>` returns
# meaningful values immediately after install, before the operator has set
# anything.
#
# Only set a key if it is not already set — this ensures that pre-seeded or
# model-configured values are not overwritten on re-install.

if [ -z "$(snapctl get port 2>/dev/null)" ]; then
    snapctl set port=8080        # <-- replace with application default
fi

if [ -z "$(snapctl get log-level 2>/dev/null)" ]; then
    snapctl set log-level=info   # <-- replace with application default
fi

# if [ -z "$(snapctl get workers 2>/dev/null)" ]; then
#     snapctl set workers=4
# fi
